### ISSUE TITLE
The apps/manage/vite.config.ts under Monorepo introduced an error when starting dev server in the "@ millipede/viteconfig" section of packages

### ISSUE THREAD

**Issue by limuen** [antitoxic/import-single-ts#1]
Hello, I saw that you asked me a question on vite issues. After I used your import-single-ts plug-in, it was normally imported, and after pnpm dev ran, An error was raised on the console. when starting dev server:TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for F:\project\millipede-admin\packages\viteconfig\index.ts This is a devastating error that works fine on a mac.

**Comment by antitoxic** [comment]
Hi @limuen. I am not planning to support `Windows` for this package. I'll close the issue and will document the limitation.
